language: d

# latest dmd
d:
  - dmd

install:
  # Install doveralls from the latest github release
  - wget -q -O - "http://bit.ly/Doveralls" | bash

script:
  - dub test -b unittest-cov
  - ./doveralls
